---
- hosts: yaum-servers
  become: true
  become_user: root
  vars:
    version: "1.0.2"
  handlers:
    - name: reload systemd
      command: systemctl daemon-reload
  tasks:
    - apt: update_cache=yes
    - apt: name="{{item}}"
      with_items:
        - redis-server
    - file: path=/yaum/current state=directory
    - name: download release
      get_url:
        url: "https://github.com/bjorand/yaum/releases/download/{{version}}/yaum_{{version}}_linux_amd64.tar.gz"
        dest: /yaum/current-{{version}}.tar.gz
      register: new_download
    - name: decompress release
      command: /bin/tar -C /yaum/current -xf /yaum/current-{{version}}.tar.gz
      when: new_download|changed
      register: new_release
    - name: service file
      copy:
        src: yaum.service
        dest: /etc/systemd/system
      notify: reload systemd
    - name: restart service on update
      service:
        name: yaum
        state: restarted
      when: new_release|changed
    - name: ensure service is started
      service:
        name: yaum
        state: started
        enabled: True
