project_name: yaum
release:
  github:
    owner: bjorand
    name: yaum
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  goarm:
  - "6"
  main: .
  ldflags: -s -w -X -X main.gitRef={{.Commit}}
  binary: yaum
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - LICENSE
  - README.md
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
