services:
  - redis-server

language: go
sudo: false

go:
  - "1.8"

before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get github.com/mattn/goveralls

install:
  - dep ensure

script:
  - $GOPATH/bin/goveralls -service=travis-ci
